name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Fetch your code
      - uses: actions/checkout@v4

      # 2) Install Flutter (this also brings in Dart)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'   # or whatever version you're on locally

      # 3) Get your pub deps
      - name: Install dependencies
        run: flutter pub get

      # 5) Build your APK
      - name: Build APK
        run: flutter build apk --release

      # 6) You can add caching, tests, etc. here…
